use_frameworks!

target 'OrangeEngineFramework_Example' do
  
  pod 'OrangeEngineFramework', :path => '../'
  pod 'AFNetworking'

  target 'OrangeEngineFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
