
source  'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'


use_frameworks!

target 'OrangeEngineFramework_Example' do
  
  pod 'OrangeEngineFramework', :path => '../'
  
  pod 'AFNetworking'
  pod 'LLCycleScrollView' 
end
