
source  'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!

target 'OrangeEngineFramework_Example' do
  
  pod 'OrangeEngineFramework', :path => '../'
  pod 'AFNetworking' ,'~>3.2.1'

  target 'OrangeEngineFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
